### ISSUE TITLE
Mosquitto SSL/TLS listener

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-MQTT-Gateway#11]
Auch SSL/TLS-Verbindungen erlauben

**Comment by christianTF** [comment]
TLS-PSK Listener ist jetzt auf Port 8883
Der PSK wird im UI angezeigt.

Beispiel-Verbindung mit mosquitto_sub:
` mosquitto_sub --psk "<psk aus dem UI>" --psk-identity loxberry  -t "#" -h localhost -p 8883`
Die psk-identity ist statisch `loxberry`
Die anderen Mosquitto-Credentials werden _nicht_ benötigt - das ist deswegen, damit man im Bridge-Mode nicht die eigenen Credentials aus der Hand geben muss (nur den PSK).

Die neue Funktion  des Bridge-Mode (https://www.loxwiki.eu/x/tgLPAg) verschiebe ich vorläufig, da ich erst den Umbau für #16 fertig mache.

**Comment by gahujipo** [comment]
im Webinterface gibt es ein Feld für den PSK, welches readonly ist. Wie kann man den PSK setzen?

**Comment by christianTF** [comment]
Moved to https://github.com/mschlenstedt/Loxberry/issues/1379
