### ISSUE TITLE
Plugin-Upgrade resets external broker password

### ISSUE THREAD

**Issue by hagor** [christianTF/LoxBerry-Plugin-MQTT-Gateway#14]
Bei Verwendung eines externen Brokers wird nach dem Upgrade das bestehende Passwort mit einem zufälligen überschrieben.
Im Log wird beim Neustart nach dem Upgrade "Check host/port/user/pass and your connection." gemeldet. Nach Eingabe des Secure-Pins steht auch in den Settings unter "MQTT Broker password" ein zufällig generiertes Passwort und nicht das korrekte, vor dem Upgrade gesetzte.
Sobald das Passwort korrigiert und gespeichert wird läuft alles wieder normal.

**Comment by christianTF** [comment]
Danke für die Meldung!

Noch eine Rückfrage zum Reproduzieren:
Verwendest du am externen Broker User und Pass, oder meldest du anonym an?

**Comment by hagor** [comment]
Immer gerne :-)

User und Passwort

**Comment by christianTF** [comment]
Ich konnte das bei mir jetzt leider nicht reproduzieren.

Irgendeinen Bug hab ich mit der Mosquitto-Auth mal gefixt, vielleicht liegt es daran.

Kannst du probieren, einfach nochmal das gleiche Update von 0.7.1 auf 0.7.1 zu machen - passiert es dann bei dir trotzdem wieder?

**Comment by hagor** [comment]
Gerade getestet, passiert beim Update von 0.7.1 auf 0.7.1 auch wieder.

**Comment by christianTF** [comment]
Danke, muss ich noch mehr ausprobieren.

**Comment by christianTF** [comment]
Tut mir leid, es passiert bei mir einfach nicht....

Kannst du bitte mal das File beobachten:
`/opt/loxberry/config/plugins/mqttgateway/cred.json`
1. Vor dem Setup 
2. Aus dem Verzeichnis raus (wird während dem Setup gelöscht)
3. Wieder schauen, nach dem Setup
4. Nochmal schauen, nach einem Reboot

Außerdem - fällt mir grad ein - kann es sein, dass da vielleicht der Browser was automatisch ausfüllt?
Genutzt werden jedenfalls die Credentials, die im cred.json stehen.

lg, Christian

**Comment by christianTF** [comment]
PS: 
Hier ist der Code, der die neuen Credentials generiert:
https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/blob/79421437b4b77d413386f1232cd3b3c5f0b756a3/bin/updateconfig.pl#L125

Sprich:
Wenn die Datei /etc/mosquitto/conf.d/mqttgateway.conf nicht existiert, wird ein neuer User/Pass erstellt. 
Trifft das möglicherweise bei dir zu?

**Comment by hagor** [comment]
Ja die Credentials im cred.json werden beim Upgrade komplett neu gesetzt.

Liegt tatsächlich an dem Check auf die mqttgateway.conf. Das File gibt es bei mir nicht.
Wurde wohl nie angelegt da ich den lokalen Broker nie verwendet habe.

**Comment by hagor** [comment]
Mit der zusätzlichen Bedingung sollte es funktionieren.

Habe testweise das mqttgateway.conf angelegt und schon bleibt mein user/passwort unangetastet beim Update ;-)

**Comment by christianTF** [comment]
Sollte passen jetzt, ich muss aber auch noch einige Tests für die neuen Features machen!

**Comment by hagor** [comment]
Klingt gut, besten Dank!
