### ISSUE TITLE
Incoming Overview unbedienbar

### ISSUE THREAD

**Issue by mschlenstedt** [christianTF/LoxBerry-Plugin-MQTT-Gateway#18]
Ich bekomme aktuell "nur" 400 Topics von insgesamt 3 Homemtic-Geräten am Gateway herein (wieso sind das eigentlich soviele?!). Die Seetie "Incoming Overview" ist dabei durch die Aktualisierung quasi unbedienbar: Scrollen - 4 Sekunden warten - scrollen - 4 Sekunden warten etc. Ans Ende der Liste komme ich so nie.

Nutze Chrome.

**Comment by christianTF** [comment]
Performance-Optimierung UI
- [ ] HTTP und UDP nur rendern, wenn aufgeklappt
- [ ] Update-Intervall einstellbar bzw. abschaltbar (Achtung wegen Checkboxen)
- [ ] Neu rendern nur bei Änderungen (Checkboxen)

**Comment by christianTF** [comment]
Kannst du mal den aktuellen Master probieren, wie das jetzt ist.
Ich habe mit 507 Einträgen getestet.

Anpassungen:
- HTTP und UDP wird nur noch gerendert, wenn es auch aufgeklappt ist.
- Aufklappen von HTTP schließt automatisch UDP und vice versa
- Beim Refresh war das Löschen der Zeilen sehr langsam -> anders implementiert
- Das Update-Intervall wird jetzt abhängig von der Anzahl der Einträge berechnet (zwischen 1 und 10 Sekunden)
- Bei den Checkboxen in der "Advanced Table View" habe ich das jQuery Mobile Rendering deaktiviert (sind jetzt "klassische" Checkboxen).

Das Entfernen des jQm-Rendering der "Reset after send" und "Disable cache" Checkboxen hat den HTTP-Overview-Rendering bei meinen 507 Einträgen von 8,5 Sekunden auf ca. 0,55 Sekunden reduziert.
Ohne "Advanced table view" rendert die HTTP-Overview jetzt in 0,2 Sekunden.

**Comment by christianTF** [comment]
https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/releases/tag/0.8.3

**Comment by mschlenstedt** [comment]
Funktioniert! 796 Einträge bei mir.

**Comment by christianTF** [comment]
Perfekt!
