### ISSUE TITLE
Making the log level selectable

### ISSUE THREAD

**Issue by hagor** [christianTF/LoxBerry-Plugin-MQTT-Gateway#51]
It could be useful to make the log level selectable as already done in other plugins.
Seems to be on Info per default.

![image](https://user-images.githubusercontent.com/12829879/92884436-22e14a00-f412-11ea-9dbb-7e82379b2cab.png)

**Comment by christianTF** [comment]
I know 😁

Currently this is not a big issue, as the log runs to the RAM disk and is cleaned up by LoxBerry.

**Comment by hagor** [comment]
I thought so, just wanted to have it written down ;-)

**Comment by christianTF** [comment]
Implemented with https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/commit/9c73ab02c906625f11cc047742c7e0629a4e97c9

No noticeable performance effect, but „LoxBerry Standard“
