### ISSUE TITLE
Spec Issue: Do not forward

### ISSUE THREAD

**Issue by JackAAnders** [christianTF/LoxBerry-Plugin-MQTT-Gateway#62]
Hi Christian,

I had the issue that outputs were changing all the time. Which led to the blinds moving up and down all the time.
When using an analog output in Loxone to publish a topic, it lead to changing values, although the output was driven with a constant value in Loxone. Finally I found that the "do not forward" option prevents the current value of beeing feed into the output again. 
I would suggest to recommend that the do not forward option is activated for analog outputs from loxone.

After I had activated the option this feedback loop was broken up and everything was working as expected.

**Comment by christianTF** [comment]
Hello Jack,
is the name of the _output_ equal to the name the Gateway is returning the data to? Then, you have created a loop.
_Do not call a **publishing output** equal to the name the Gateway is sending to._ Use any other name for the output. 

In general, it is hard to give recommendations as I don't know every data passing the Gateway, so I cannot say if the recommendation is valid for every use-case.
