### ISSUE TITLE
MQTT Publish with a space

### ISSUE THREAD

**Issue by knallt** [christianTF/LoxBerry-Plugin-MQTT-Gateway#81]
Hey, 

I installed 2.0.1 PRE-RELEASE. 
Is it possible that there is a publish error from the mini server? 

I have several topics sending 1 or 0 for switches. Since the new Release they don't work anymore. But if I publish from another source (e.g. Quick Publisher) it works. 

Now I checked the logs and discovered hat topics from the mini server contain an additional space after the value:

**from Quick Publisher:**

```
18:08:06.499 OK: UDP IN: localhost (127.0.0.1): {"value":"0","retain":"false","topic":"loxone/bad2/motion"}
18:08:06.499 Publishing: 'loxone/bad2/motion'='0'
18:08:06.513 INFO: MQTT received: loxone/bad2/motion: 0
```

**from Miniserver:**

```
18:05:36.532 OK: UDP IN:  (10.10.10.24): publish loxone/bad2/motion 0
18:05:36.532 Checking if transformer requested
18:05:36.533 Publishing: 'loxone/bad2/motion'='0 '
18:05:36.535 INFO: MQTT received: loxone/bad2/motion: 0 
```
--> line 3 it contains the space after the 0. There is no space in the publish from the mini-server.

Is this maybe a bug in the PRE-RELEASE?

**Comment by christianTF** [comment]
I'll check that.
I already got another issue but couldn't reproduce. But I haven't tested directly from the Miniserver but from the Bash sending UDP messages.
I will do the check again from the Miniserver.
Thanks for annotation.
Christian

**Comment by christianTF** [comment]
I think I've found it:
https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/blob/f9ef90556d5a8cd465334378af079338effdfb3d/bin/mqttgateway.pl#L291

As the last variable is empty, the blank is added.

I'll fix that today and will do a 2.0.2 Prerelease immediately.

**Comment by knallt** [comment]
Ah. Very cool! 
Thank you, Christian.

**Comment by knallt** [comment]
Installed 2.0.2. funzt alles wieder!
