### ISSUE TITLE
Gateway and/or MQTT Server needs reset

### ISSUE THREAD

**Issue by JochenKoehler69** [christianTF/LoxBerry-Plugin-MQTT-Gateway#93]
In my installation it seems that the MQTT hub and or the MQTT server hangs up sometimes. At least some messages aren't sent anymore to devices. When I restart the gateway with the web-UI, everything works fine again.
Is it possible to restart these processes automatically on a regular basis to mitigate this problem at least?

**Comment by christianTF** [comment]
Servus Jochen,

ich möchte keine Maßnahmen treffen, ohne die Ursache zu kennen.

Wenn dieser Vorfall auftritt, bitte:
- LoxBerry Healthcheck durchführen
- Status der Services (Gateway und Broker) aus der Plugin-Seite
- Vollständiges Logfile des MQTT Gateway.

lg, Christian

**Comment by christianTF** [comment]
Close because of inactivity.
